language: python
python:
  - "3.2"
  - "3.3"
  - "3.4"
  - "2.7"

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
  - git clone --quiet --depth=100 "https://github.com/nanomsg/nanomsg.git" ~/builds/nanomsg
      && pushd ~/builds/nanomsg
      && ./autogen.sh
      && ./configure
      && make
      && sudo make install
      && popd;

before_script: make install
script:  LD_LIBRARY_PATH=/lib:/usr/lib:/usr/local/lib make test