sudo: required
dist: bionic

language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7"

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y software-properties-common
  - sudo add-apt-repository -y -u ppa:ubuntu-toolchain-r/test
  - sudo apt-get -qq update
  - sudo apt-get install -y --allow-unauthenticated build-essential cmake

install:
  - git clone --quiet --depth=100 "https://github.com/nanomsg/nanomsg.git" ~/builds/nanomsg
      && pushd ~/builds/nanomsg
  - export TRAVIS_TAG=$(cat .version)
  - git checkout -b "${TRAVIS_TAG}"
  - mkdir build && cd build
  - cmake ..
  - cmake --build .
  - ctest -C Debug .
  - sudo cmake --build . --target install
  - sudo ldconfig && popd
  - pip install tox-travis pathlib2

before_script:
  - make install
#  - export TEST_ARGS="--exclude=test_.*execute"

# command to run tests, e.g. python setup.py test
script:
  - tox
